backend:
  name: github
  repo: besohard/besohard-site
  branch: main
  auth_endpoint: https://api.netlify.com


media_folder: "content/images"
public_folder: "/content/images"

collections:
  - name: "posts"
    label: "Insights"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Content", name: "body", widget: "markdown" }
